language: node_js

node_js:
  - 10

stages:
  - continousIntegration
  - continousDelivery

before_install:
  - chmod +x gradlew
  - sudo apt-get update

install:
  - sudo apt install curl
  - npm install -g newman

jobs:
  include:
    - stage: continousDelivery
      deploy:
        provider: heroku
        api-key: $HEROKU_API_KEY
        app: $HEROKU_STAGING_APP
